name: First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first github actions page"
            
            - name: List Files
              run: ls

            - name: Read File
              run: cat README.md