name: Gerar Arte Tres

on: push

jobs:
    gerar_arte:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Gerar Arte
              run: cowsay -f cow "Hello cow" >> cow.txt

    ler_arte:
        runs-on: ubuntu-latest
        steps:
            - name: Ler Arquivo
              run: cat cow.txt