name: Terceiro Frost

on: push

jobs:
    frost_tres:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4
            
            - name: My File
              run: |
                mkdir teste
                touch ./teste/srdamex.txt
                echo "Damex Apelao" >> ./teste/srdamex.txt
                cat ./teste/srdamex.txt
                ls