name: Matrix Configuration

on: 
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:

          fail-fast: false
          max-parallel: 2

          matrix:
            os_to_run: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images_to_test: [hello-world, alpine]

            exclude:
              - images_to_exclude: alpine
                os_to_exclude_image: windows-latest
            include:
              - images_to_include: amd64/alpine
                os_to_include_image: ubuntu-20.04

        runs-on: ${{matrix.os_to_run}}
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Image on ${{matrix.os_to_run}}
              run: docker run ${{matrix.images_to_test}}