name: Workflow Filters and Activities

on: 
    workflow_dispatch:
    push:
      # branches-ignore: 
      #    - feature/* #feature/add-music, feature/update-images
      #    - test/* #test/ui/index, test/checkout/payment
      branches: 
        - main
        - '!feature/*' #ignoring pushing to any branch name starting with feature using!

    pull_request:
      types: 
        - opened
        - closed
      paths-ignore: # workflow will only run when a pull request that includes a change on any file other than README.md
        - README.md
      branches: 
        - main # configure your workflow to only run on pull requests that target specif branches.

    # schedule:
    #   - cron: "*/59 * * * *"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Nothing
            run: echo this workflow/job/step is executed for event type  - ${{github.event_name}}

